services:
  nginx:
    volumes:
      - /opt/worksmart/runtime/gateway-nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    networks:
      worksmart_gateway: {}

networks:
  worksmart_gateway:
    name: worksmart_gateway
    external: true
